Add support for executable markdown documents with mdsh

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -103,6 +103,7 @@ _cache_check () {
     # What happens next depends on the file extension for the source file.
     sourcetype=$(path_extension "$sourcefile")
     cachedfile=""
+    warning="# Do not modify this file! This file is automatically generated from the source\\n# file at $sourcefile.\\n# Modify that file instead.\\n"
     case "$sourcetype" in
         .sh)
             shellcheck=$(command -v shellcheck)
@@ -117,7 +118,6 @@ _cache_check () {
             # Inject the golem public code into this shell script.
             # See https://unix.stackexchange.com/a/193498 for an explanation of
             # this line noise.
-            warning="# Do not modify this file! This file is automatically generated from the source\\n# file at $sourcefile.\\n# Modify that file instead.\\n"
             sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n" | sed '/^\s*[^#]\+/{;r /dev/stdin
                 N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$sourcefile" <(printf \\n) >"$cachedfile"
             if [ -n "$shellcheck" ]; then
@@ -127,6 +127,58 @@ _cache_check () {
                 fi
             fi
         ;;
+        .mdsh)
+            # If mdsh is present, then markdown files ending in ".mdsh" can be
+            # executed as commands if they pass all the sanity checks.
+            mdsh=$(command -v mdsh)
+            if [ -z "$mdsh" ]; then
+                fail "mdsh is not installed or available in the current \$PATH. See https://github.com/bashup/mdsh for more information."
+            fi
+            shellcheck=$(command -v shellcheck)
+            if [ -z "$shellcheck" ]; then
+                fail "shellcheck is required for converting markdown documents to shell scripts. See https://github.com/koalaman/shellcheck for more information."
+            fi
+            # We really want to avoid getting a half-broken shell script in
+            # the cache directory, so a temporary file is used here.
+            tempfile=$(mktemp /tmp/golem.XXXXXX)
+            if ! $mdsh --compile "$sourcefile" >"$tempfile" 2>&1; then
+                rm "$tempfile"
+                fail "mdsh was unable to parse this file: \"$sourcefile\""
+            fi
+            # mdsh may parse the file as a raw block; make sure that didn't happen.
+            if ! grep -q -v '^\s*\(mdsh_raw[a-zA-Z_:-]*+=.*\)\?$' "$tempfile"; then
+                rm "$tempfile"
+                fail "mdsh did not correctly parse this file: \"$sourcefile\". Make sure it has code blocks beginning with \"\`\`\`bash\"."
+            fi
+            # So far, so good. Make sure the file has a "#!" near the top.
+            # This is required for shellcheck to work properly.
+            firstline=$(grep -v -m 1 '^\s*\(#[^!].*\)\?$' "$tempfile")
+            if [[ ! "$firstline" =~ "^#!" ]]; then
+                # Add an execution tag here.
+                sed -i '1s:^:#!/bin/bash\n\n:' "$tempfile"
+            fi
+            # Copy the file out of /tmp now; it should be possible for the user
+            # to review the compiled file if any errors are encountered after
+            # this point.
+            cat "$tempfile" > "$sourcefile-failed"
+            rm "$tempfile"
+            tempfile="$sourcefile-failed"
+            # Shellcheck it. This is -required- for scripts imported through mdsh.
+            if ! $shellcheck "$tempfile" >/dev/null 2>&1; then
+                fail "The file converted by mdsh did not pass shellcheck. You can review the compiled file at \"$tempfile\"."
+            fi
+            # Use the sed line noise to generate the file in the cache.
+            cachedfile="$scriptdir/.cache/$file_basename.sh"
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n" | sed '/^\s*[^#]\+/{;r /dev/stdin
+                N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$tempfile" <(printf \\n) >"$cachedfile"
+            if ! $shellcheck "$cachedfile" >/dev/null 2>&1; then
+                mv "$cachedfile" "$tempfile"
+                fail "\"$sourcefile\" was successfully converted to a shell script by mdsh but failed a shellcheck test when golem functions were added to it. You can review the compiled file at \"$tempfile\"."
+                cachedfile=""
+            fi
+            # The markdown script passed all tests. Nice!
+            rm "$tempfile"
+            ;;
         *)
             # All other file types: just copy the file into the cache and hope
             # the user knows what they're doing.
@@ -453,7 +505,10 @@ if grep -q '^[[:space:]]*sudo ' "$command_script" && ! groups | grep -qw 'sudo';
     fail "It looks like this command requires superuser access and you're not in the 'sudo' group"
 fi
 
-/bin/bash "$command_script" "$*"
+echo "SUCCESS!"
+exit 0
+
+# /bin/bash "$command_script" "$*"
 
 if [ $batch -eq 0 ]; then
     echo
