Add a 'sudo warmup' to command scripts.
I'm running into a problem where script execution is sort-of-kind-of pausing on the first 'sudo' command; while sudo waits for a password, some or all of the remaining script gets read into stdin, making it impossible to enter a correct password and also causing script execution to be inconsistent.

If the password is entered correctly on the second attempt, some of the script commands don't get re-executed. It's a mess.

I hope that using 'sudo' in an if...then block will resolve this.

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -97,6 +97,7 @@ _cache_check () {
     sourcetype=$(path_extension "$sourcefile")
     cachedfile=""
     warning="# Do not modify this file! This file is automatically generated from the source\\n# file at $sourcefile.\\n# Modify that file instead.\\n"
+    sudowarmup="# This script appears to require sudo, so make sure the user has the necessary access.\\n# If they do, then run a sudo command now so that script execution doesn't trip\\n# on a password prompt later.\\nif ! groups | grep -qw 'sudo'; then\\n    fail \"It looks like this command script requires superuser access and you're not in the 'sudo' group\"\\nelif [ \"\$(sudo whoami)\" != \"root\" ]; then\\n    fail \"Your 'sudo' command seems to be broken\"\\nfi\\n\\n"
     case "$sourcetype" in
         .sh)
             shellcheck=$(command -v shellcheck)
@@ -108,10 +109,14 @@ _cache_check () {
             fi
             # Shellcheck succeeded or is not available.
             cachedfile="$golemdir/.cache/$file_basename.sh"
+            # Nuke the 'sudo warmup' if it's not needed for this script.
+            if ! grep -q '^[[:space:]]*sudo ' "$sourcefile"; then
+                sudowarmup=""
+            fi
             # Inject the golem public code into this shell script.
             # See https://unix.stackexchange.com/a/193498 for an explanation of
             # this line noise.
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$golempath" | xargs -0 printf "\\n$warning\\n%s\\n" | sed '/^\s*[^#]\+/{;r /dev/stdin
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$golempath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
                 N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$sourcefile" <(printf \\n) >"$cachedfile"
             if [ -n "$shellcheck" ]; then
                 # Run shellcheck one more time on the completed cached file.
@@ -164,9 +169,13 @@ _cache_check () {
             if ! $shellcheck "$tempfile" >/dev/null 2>&1; then
                 fail "The file converted by mdsh did not pass shellcheck. You can review the compiled file at \"$tempfile\"."
             fi
+            # Nuke the 'sudo warmup' if it's not needed for this script.
+            if ! grep -q '^[[:space:]]*sudo ' "$tempfile"; then
+                sudowarmup=""
+            fi
             # Use the sed line noise to generate the file in the cache.
             cachedfile="$golemdir/.cache/$file_basename.sh"
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$golempath" | xargs -0 printf "\\n$warning\\n%s\\n" | sed '/^\s*[^#]\+/{;r /dev/stdin
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$golempath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
                 N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$tempfile" <(printf \\n) >"$cachedfile"
             if ! $shellcheck "$cachedfile" >/dev/null 2>&1; then
                 mv "$cachedfile" "$tempfile"
@@ -503,11 +512,7 @@ command_script=$(_shell_resolve_cmd "$*")
 if [ -z "$command_script" ]; then
     fail "No matching command script found for \"$*\""
 fi
-
-if grep -q '^[[:space:]]*sudo ' "$command_script" && ! groups | grep -qw 'sudo'; then
-    fail "It looks like this command requires superuser access and you're not in the 'sudo' group"
-fi
-
+exit 0
 /bin/bash "$command_script" "$*"
 
 if [ $batch -eq 0 ]; then
