, , etc. -> , , etc.

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -29,7 +29,7 @@ _find_cmd_file () {
     shift
     for lookdir in "$@"; do
         # Ensure the directory exists.
-        if [ ! -d "$scriptdir/$lookdir" ]; then
+        if [ ! -d "$mydir/$lookdir" ]; then
             continue
         fi
         # Iterate over the list of files in this directory from longest file
@@ -42,7 +42,7 @@ _find_cmd_file () {
         # which prevents later code from accessing any variables that are set,
         # exit doesn't work because the pipe is a subshell (it just exits the
         # pipe). So ... early return from a function!
-        for scriptfile in "$scriptdir"/"$lookdir"/*.{sh,md,mdsh}; do echo ${#scriptfile} "$scriptfile"; done | sort -rn | cut -d " " -f 2 | while read -r filename; do
+        for scriptfile in "$mydir"/"$lookdir"/*.{sh,md,mdsh}; do echo ${#scriptfile} "$scriptfile"; done | sort -rn | cut -d " " -f 2 | while read -r filename; do
             if [ ! -f "$filename" ]; then
                 # "Null globbing": patterns which don't match any files will
                 # return the pattern. `shopt -s nullglob` also fixes this, but
@@ -71,11 +71,11 @@ _cache_update ()
     filename="$1"
     file_basename="$(path_basename "$filename")"
     # Delete any previous "-failed" scripts (files that did not successfully get imported).
-    find -P "$scriptdir/scripts" -maxdepth 1 -name "$file_basename.*-failed" -delete
-    sourcefiles=("$scriptdir"/scripts/"$file_basename".*)
+    find -P "$mydir/scripts" -maxdepth 1 -name "$file_basename.*-failed" -delete
+    sourcefiles=("$mydir"/scripts/"$file_basename".*)
     if [ ${#sourcefiles[@]} -gt 1 ]; then
-        fail "There are multiple files in the $scriptdir/scripts matching the pattern $file_basename.*. There should be only one match for that pattern. Please rename some of them."
-    elif [ ${#sourcefiles[@]} -lt 1 ] || [ "${sourcefiles[0]}" = "$scriptdir/scripts/$file_basename.*" ]; then
+        fail "There are multiple files in the $mydir/scripts matching the pattern $file_basename.*. There should be only one match for that pattern. Please rename some of them."
+    elif [ ${#sourcefiles[@]} -lt 1 ] || [ "${sourcefiles[0]}" = "$mydir/scripts/$file_basename.*" ]; then
         fail "The original source file matching \"$file_basename\" has disappeared."
     fi
     sourcefile="${sourcefiles[0]}"
@@ -98,7 +98,7 @@ _cache_update ()
                 fi
             fi
             # Shellcheck succeeded or is not available.
-            cachedfile="$scriptdir/.cache/$file_basename.sh"
+            cachedfile="$mydir/.cache/$file_basename.sh"
             # Nuke the 'sudo warmup' if it's not needed for this script.
             if ! grep -q '^[[:space:]]*\(if[[:space:]]*\)\?sudo ' "$sourcefile"; then
                 sudowarmup=""
@@ -106,7 +106,7 @@ _cache_update ()
             # Inject the golem public code into this shell script.
             # See https://unix.stackexchange.com/a/193498 for an explanation of
             # this line noise.
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$mypath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
                 N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$sourcefile" <(printf \\n) >"$cachedfile"
             # Add a wrapper around apt installations to catch errors and force
             # bash to wait until the installation is concluded.
@@ -168,8 +168,8 @@ _cache_update ()
                 sudowarmup=""
             fi
             # Use the sed line noise to generate the file in the cache.
-            cachedfile="$scriptdir/.cache/$file_basename.sh"
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
+            cachedfile="$mydir/.cache/$file_basename.sh"
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$mypath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
                 N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$tempfile" <(printf \\n) >"$cachedfile"
             # Add a wrapper around apt installations to catch errors and force
             # bash to wait until the installation is concluded.
@@ -187,7 +187,7 @@ _cache_update ()
             # All other file types: just copy the file into the cache and hope
             # the user knows what they're doing.
             filename=$(path_filename "$sourcefile")
-            cachedfile="$scriptdir/.cache/$filename"
+            cachedfile="$mydir/.cache/$filename"
             cp "$sourcefile" "$cachedfile"
         ;;
     esac
@@ -238,18 +238,18 @@ _import_script () {
         destfile=$(echo "$destcmd" | sed 's/ \+/_/g')
         dest_ext=$(path_extension "$sourcefile")
         # Don't remove or overwrite the file that's about to be imported if the user tries to do that. (!)
-        if [ "$(realpath -m "$scriptdir/scripts/$destfile$dest_ext")" != "$(realpath -m "$sourcefile")" ]; then
-            matched=$(find -P "$scriptdir/scripts" -maxdepth 1 -name "$destfile.*")
+        if [ "$(realpath -m "$mydir/scripts/$destfile$dest_ext")" != "$(realpath -m "$sourcefile")" ]; then
+            matched=$(find -P "$mydir/scripts" -maxdepth 1 -name "$destfile.*")
             if [ -n "$matched" ]; then
                 matched=$(path_filename "$matched")
                 if ! ask "\"$destcmd\" matches the file \"$matched\" in scripts/. Do you want to replace this file?"; then
                     echo "Canceled."
                     exit 1
                 else
-                    rm "$scriptdir/scripts/$matched"
+                    rm "$mydir/scripts/$matched"
                 fi
             fi
-            if ! cp "$sourcefile" "$scriptdir/scripts/$destfile$dest_ext"; then
+            if ! cp "$sourcefile" "$mydir/scripts/$destfile$dest_ext"; then
                 fail "Copy failed."
             fi
         fi
@@ -272,13 +272,13 @@ _import_script () {
 _cache_check () {
     file_basename="$1"
     # Locate matching source and cache file(s).
-    sourcefiles=("$scriptdir"/scripts/"$file_basename".*)
-    cachedfiles=("$scriptdir"/.cache/"$file_basename".*)
+    sourcefiles=("$mydir"/scripts/"$file_basename".*)
+    cachedfiles=("$mydir"/.cache/"$file_basename".*)
     # See if a cache update can be skipped.
     # The current version of bash should return a single-element array containing
     # the input glob if no matches were found, but future versions may change
     # this behavior.
-    if [ ${#cachedfiles[@]} -eq 1 ] && [ ${#sourcefiles[@]} -eq 1 ] && [ "${cachedfiles[0]}" != "$scriptdir/.cache/$file_basename.*" ] && [ "${sourcefiles[0]}" != "$scriptdir/scripts/$file_basename.*" ]; then
+    if [ ${#cachedfiles[@]} -eq 1 ] && [ ${#sourcefiles[@]} -eq 1 ] && [ "${cachedfiles[0]}" != "$mydir/.cache/$file_basename.*" ] && [ "${sourcefiles[0]}" != "$mydir/scripts/$file_basename.*" ]; then
         # Try a hash comparison first.
         cached_hash="$(head -n 10 "${cachedfiles[0]}" | grep -oP '(?<=^# source hash: )[0-9a-f]{32}')"
         if [ -n "$cached_hash" ] && [ "$cached_hash" = "$(md5sum "${sourcefiles[0]}" | grep -oP '^[0-9a-f]{32}')" ]; then
@@ -345,13 +345,13 @@ _shell_resolve_cmd () {
 
 # Use any of these as necessary.
 # shellcheck disable=SC2034
-scriptpath=$(readlink -m "$BASH_SOURCE")
+mypath=$(readlink -m "$BASH_SOURCE")
 # shellcheck disable=SC2034
-scriptname=$(basename "$scriptpath")
+myname=$(basename "$mypath")
 # shellcheck disable=SC2034
-scriptdir=$(dirname "$scriptpath")
+mydir=$(dirname "$mypath")
 # shellcheck disable=SC2034
-scriptshell=$(readlink /proc/$$/exe)
+myshell=$(readlink /proc/$$/exe)
 
 # Exit with an error if an undefined variable is referenced.
 set -u
@@ -447,7 +447,7 @@ warn () {
 #
 fail () {
     echo "ERROR: $*" | fmt -w 80 >&2
-    pkill -TERM -g $$ "$scriptname" || kill TERM $$ >/dev/null 2>&1
+    pkill -TERM -g $$ "$myname" || kill TERM $$ >/dev/null 2>&1
     exit 1
 }
 
@@ -752,14 +752,14 @@ fi
 # A "scripts" directory should be present in the parent directory.
 # This doesn't get automatically fixed because it's indicative of something
 # unusual about the environment.
-if [ ! -d "$scriptdir/scripts" ]; then
-    fail "The \"scripts\" directory is missing from \"$scriptdir\". It should have been included in the repository. Please create it manually."
+if [ ! -d "$mydir/scripts" ]; then
+    fail "The \"scripts\" directory is missing from \"$mydir\". It should have been included in the repository. Please create it manually."
 fi
 # The .cache directory should exist because _import_script() uses it to sanity-
 # check the environment. This can be created if it's not present.
-if [ ! -d "$scriptdir/.cache" ]; then
-    if ! mkdir -p "$scriptdir/.cache"; then
-        fail "\"$scriptdir/.cache doesn't exist and could not be created. Please create it manually and try again."
+if [ ! -d "$mydir/.cache" ]; then
+    if ! mkdir -p "$mydir/.cache"; then
+        fail "\"$mydir/.cache doesn't exist and could not be created. Please create it manually and try again."
     fi
 fi
 
@@ -774,7 +774,7 @@ else
     fi
     if [ ${#destinations[@]} -eq 0 ]; then
         # No remote destinations, run command script locally.
-        $scriptshell "$command_script" "$(printf '%q ' "${longopts[@]}" "$@")"
+        $myshell "$command_script" "$(printf '%q ' "${longopts[@]}" "$@")"
     else
         # One or more remote destinations.
         # Start by converting the selected command script into a base64 blob.
