Add the "import script" primitive and update .gitignore

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -80,125 +80,10 @@ _cache_check () {
         fi
     fi
     # One of the above tests failed, so the cache needs to be updated.
-    if [ ${#sourcefiles[@]} -gt 1 ]; then
-        fail "There are multiple files in the $scriptdir/scripts matching the pattern $file_basename.*. There should be only one match for that pattern. Please rename some of them."
-    fi
-    # Delete any copies of this file currently in the cache.
-    find -P "$scriptdir/.cache" -maxdepth 1 -name "$file_basename.*" -delete
-    if [ ${#sourcefiles[@]} -lt 1 ] || [ "${sourcefiles[0]}" = "$scriptdir/scripts/$file_basename.*" ]; then
-        # The original source file has disappeared. In this case, there's nothing
-        # more for the _cache_update() function to do. If this is an error
-        # condition, it will be handled elsewhere.
-        echo ""
-        return 0
-    fi
-    sourcefile="${sourcefiles[0]}"
-    # What happens next depends on the file extension for the source file.
-    sourcetype=$(path_extension "$sourcefile")
-    cachedfile=""
-    warning="# Do not modify this file! This file is automatically generated from the source\\n# file at $sourcefile.\\n# Modify that file instead.\\n"
-    sudowarmup="# This script appears to require sudo, so make sure the user has the necessary access.\\n# If they do, then run a sudo command now so that script execution doesn't trip\\n# on a password prompt later.\\nif ! groups | grep -qw 'sudo'; then\\n    fail \"It looks like this command script requires superuser access and you're not in the 'sudo' group\"\\nelif [ \"\$(sudo whoami)\" != \"root\" ]; then\\n    fail \"Your 'sudo' command seems to be broken\"\\nfi\\n\\n"
-    case "$sourcetype" in
-        .sh)
-            shellcheck=$(command -v shellcheck)
-            if [ -n "$shellcheck" ]; then
-                # Run shellcheck on the source file before using it, if available.
-                if ! $shellcheck "$sourcefile" >/dev/null 2>&1; then
-                    fail "The shell file in $sourcefile has changed and the new version isn't passing shellcheck. Please run \"shellcheck $sourcefile\" and then try again."
-                fi
-            fi
-            # Shellcheck succeeded or is not available.
-            cachedfile="$scriptdir/.cache/$file_basename.sh"
-            # Nuke the 'sudo warmup' if it's not needed for this script.
-            if ! grep -q '^[[:space:]]*sudo ' "$sourcefile"; then
-                sudowarmup=""
-            fi
-            # Inject the golem public code into this shell script.
-            # See https://unix.stackexchange.com/a/193498 for an explanation of
-            # this line noise.
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
-                N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$sourcefile" <(printf \\n) >"$cachedfile"
-            if [ -n "$shellcheck" ]; then
-                # Run shellcheck one more time on the completed cached file.
-                if ! $shellcheck "$cachedfile" >/dev/null 2>&1; then
-                    fail "There was a conflict between \"$sourcefile\" and the golem code that gets added to command scripts. Please run \"shellcheck $cachedfile\" and then try again."
-                fi
-            fi
-        ;;
-        .mdsh)
-            # If mdsh is present, then markdown files ending in ".mdsh" can be
-            # executed as commands if they pass all the sanity checks.
-            mdsh=$(command -v mdsh)
-            if [ -z "$mdsh" ]; then
-                fail "mdsh is not installed or available in the current \$PATH. See https://github.com/bashup/mdsh for more information."
-            fi
-            shellcheck=$(command -v shellcheck)
-            if [ -z "$shellcheck" ]; then
-                fail "shellcheck is required for converting markdown documents to shell scripts. See https://github.com/koalaman/shellcheck for more information."
-            fi
-            # We really want to avoid getting a half-broken shell script in
-            # the cache directory, so a temporary file is used here.
-            tempfile=$(mktemp /tmp/golem.XXXXXX)
-            # The next line constructs a special mdsh function to handle "bash"
-            # language blocks; it natively only handles "shell" language blocks.
-            # That function gets injected into the top of the input and then
-            # passed to mdsh.
-            if ! echo -e '```shell @mdsh\nmdsh-compile-bash(){ printf "%s" "$1";}\n```\n\n' | cat - "$sourcefile" | $mdsh --compile - >"$tempfile" 2>&1; then
-                rm "$tempfile"
-                fail "mdsh was unable to parse this file: \"$sourcefile\""
-            fi
-            # mdsh may parse the file as a raw block; make sure that didn't happen.
-            if ! grep -q -v '^\s*\(mdsh_raw[a-zA-Z_:-]*+=.*\)\?$' "$tempfile"; then
-                rm "$tempfile"
-                fail "mdsh did not correctly parse this file: \"$sourcefile\". Make sure it has code blocks beginning with \"\`\`\`bash\"."
-            fi
-            # So far, so good. Make sure the file has a "#!" near the top.
-            # This is required for shellcheck to work properly.
-            firstline=$(grep -v -m 1 '^\s*\(#[^!].*\)\?$' "$tempfile")
-            if [[ ! "$firstline" =~ "^#!" ]]; then
-                # Add an execution tag here.
-                sed -i '1s:^:#!/bin/bash\n\n:' "$tempfile"
-            fi
-            # Copy the file out of /tmp now; it should be possible for the user
-            # to review the compiled file if any errors are encountered after
-            # this point.
-            cat "$tempfile" > "$sourcefile-failed"
-            rm "$tempfile"
-            tempfile="$sourcefile-failed"
-            # Shellcheck it. This is -required- for scripts imported through mdsh.
-            if ! $shellcheck "$tempfile" >/dev/null 2>&1; then
-                fail "The file converted by mdsh did not pass shellcheck. You can review the compiled file at \"$tempfile\"."
-            fi
-            # Nuke the 'sudo warmup' if it's not needed for this script.
-            if ! grep -q '^[[:space:]]*sudo ' "$tempfile"; then
-                sudowarmup=""
-            fi
-            # Use the sed line noise to generate the file in the cache.
-            cachedfile="$scriptdir/.cache/$file_basename.sh"
-            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\\n$warning\\n%s\\n$sudowarmup" | sed '/^\s*[^#]\+/{;r /dev/stdin
-                N;:l;$!n;$!bl;};${;/^$/!{;s/\\n$//;};//d;}' "$tempfile" <(printf \\n) >"$cachedfile"
-            if ! $shellcheck "$cachedfile" >/dev/null 2>&1; then
-                mv "$cachedfile" "$tempfile"
-                fail "\"$sourcefile\" was successfully converted to a shell script by mdsh but failed a shellcheck test when golem functions were added to it. You can review the compiled file at \"$tempfile\"."
-                cachedfile=""
-            fi
-            # The markdown script passed all tests. Nice!
-            rm "$tempfile"
-            ;;
-        *)
-            # All other file types: just copy the file into the cache and hope
-            # the user knows what they're doing.
-            filename=$(path_filename "$sourcefile")
-            cachedfile="$scriptdir/.cache/$filename"
-            cp "$sourcefile" "$cachedfile"
-        ;;
-    esac
-    if [ -n "$cachedfile" ]; then
-        chmod 0775 "$cachedfile"
-        touch -r "$sourcefile" "$cachedfile"
-    fi
-    echo "$cachedfile"
-    return 0
+    # shellcheck source=scripts/import_script.sh
+    . "$scriptdir"/scripts/import_script.sh
+    _import_script "${sourcefiles[0]}"
+    return $?
 }
 
 
@@ -338,7 +223,7 @@ random_string () {
 # Write a message to stderr and continue execution.
 #
 warn () {
-    echo "Warning: $*" >&2
+    echo "Warning: $*" | fmt -w 80 >&2
 }
 
 
@@ -346,7 +231,7 @@ warn () {
 # Write a message to stderr and exit immediately with a non-zero code.
 #
 fail () {
-    echo "ERROR: $*" >&2
+    echo "ERROR: $*" | fmt -w 80 >&2
     pkill -TERM -g $$ "$scriptname" || kill TERM $$
     exit 1
 }
@@ -532,14 +417,30 @@ if [ ! -d "$scriptdir/.cache" ]; then
     fi
 fi
 
-# Process arguments
-# TODO: Full automatic argument processing before loading a script.
-command_script=$(_shell_resolve_cmd "$*")
-if [ -z "$command_script" ]; then
-    fail "No matching command script found for \"$*\""
-fi
+if [[ "$*" == "import script"* ]]; then
+    # Bootstrap a command script import. This bypasses the normal cache checks.
+    # This is the only command script that is sourced instead of exec'd.
+    # shellcheck source=scripts/import_script.sh
+    . "$scriptdir"/scripts/import_script.sh
+    # When invoked by the user, the "import script" words need to be shifted.
+    shift; shift
+    cached=$(_import_script "$@") || exit 1
+    if [ -f "$cached" ]; then
+        echo "Successfully imported $@"
+    else
+        echo "Script failed to import but the import function didn't return an error. This is a bug."
+        exit 1
+    fi
+else
+    # Process arguments
+    # TODO: Full automatic argument processing before loading a script.
+    command_script=$(_shell_resolve_cmd "$*")
+    if [ -z "$command_script" ]; then
+        fail "No matching command script found for \"$*\""
+    fi
 
-$scriptshell "$command_script" "$*"
+    $scriptshell "$command_script" "$*"
+fi
 
 if [ $batch -eq 0 ]; then
     echo
