Add support for remote servers! Woo! @server...

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -338,7 +338,7 @@ ask () {
                 if [[ ! "$ans" ]]; then ans=$default; fi
             fi
         else
-            read -r -p "$prompt" ans </dev/tty
+            read -r -p "$prompt" ans <"$(tty)"
             if [[ ! "$ans" ]]; then
                 if [ $required -eq 1 ]; then
                     warn "An answer is required."
@@ -445,28 +445,38 @@ need () {
 
 
 # Process arguments. Golem will load any "--variable value" pairs into the
-# command script's runtime. Example: if your command script needs a "hostname"
-# value, the user can supply that with, "golem --hostname 'host.name' your command",
-# and the "your_command.sh" file will have a variable named "hostname" with the
-# value "host.name".
+# "longopts" array. Your command script can then call the need() function to
+# load this value into a variable.
+# Example: if your command script needs a "hostname" value, the user can supply
+# that with, "golem --hostname 'host.name' your command", and the "your_command.sh"
+# file can use "hostname=need(hostname)" to create a variable named "hostname"
+# with the value "host.name" (or ask the user for it).
 declare -a longopts=()
+declare -a args=()
 while [ $# -gt 0 ] && [[ "$1" ]]; do
     case "$1" in
+        --)
+            # Stop processing arguments.
+            break
+            ;;
         --*)
             if [ $# -lt 2 ]; then
                 fail "Missing value for $1"
             fi
-            # These longopts need to be saved because of the way golem invokes
-            # command scripts; otherwise, it has no way to pass the arguments
-            # off to the scripts.
             longopts+=("$(printf '%s' "$1")")
             longopts+=("$(printf '%s' "$2")")
             shift 2
             ;;
         *)
-            break
+            args+=("$1")
+            shift
+            ;;
     esac
 done
+# Reset the arguments list to every argument that wasn't a --longopt.
+set -- "${args[@]}"
+unset args
+
 
 ################################################################################
 #                                                                              #
@@ -475,6 +485,25 @@ done
 ################################################################################
 
 # end-golem-injected-code
+
+
+# Extract any destinations from the arguments list.
+declare -a destinations=()
+declare -a args=()
+while [ $# -gt 0 ] && [[ "$1" ]]; do
+    case "$1" in
+        @*)
+            destinations+=("${1:1}")
+            shift
+            ;;
+        *)
+            args+=("$1")
+            shift
+            ;;
+    esac
+done
+set -- "${args[@]}"
+unset args
 
 if [ $# -lt 1 ]; then
     # TODO: Needs a help subsystem.
@@ -523,15 +552,38 @@ if [[ "$*" == "import script"* ]]; then
     if [ -f "$cached" ]; then
         echo "Successfully imported $*"
     else
-        echo "Script failed to import but the import function didn't return an error. This is a bug."
-        exit 1
+        fail "Script failed to import but the import function didn't return an error. This is a bug."
     fi
 else
     command_script=$(_shell_resolve_cmd "$*")
     if [ -z "$command_script" ]; then
         fail "No matching command script found for \"$*\""
     fi
-    $scriptshell "$command_script" "${longopts[@]}" "$*"
+    if [ ${#destinations[@]} -eq 0 ]; then
+        # No remote destinations, run command script locally.
+        $scriptshell "$command_script" "${longopts[@]}" "$*"
+    else
+        # One or more remote destinations.
+        for destination in "${destinations[@]}"; do
+            # The destination should be defined in the user's local ssh config file.
+            ssh_host=$(ssh -G "$destination" | grep -Pio '(?<=^hostname ).*$')
+            if [ -z "$ssh_host" ]; then
+                fail "your ssh configuration did not return a valid hostname for the remote destination $destination"
+            fi
+            hostaddr=$(ping -q -n -c 1 -t 1 -w 1 "$ssh_host" 2>&1 | grep -Po "\\b$ssh_host\\s+\\([^\\(\\)]+\\)")
+            if [ -z "$hostaddr" ]; then
+                fail "$destination could not be resolved to a valid network address"
+            fi
+            # Okay. Run this command script on a remote host.
+            # Doesn't work, because non-interactive:
+            # ssh -t "$destination" "bash -s -- ${longopts[*]} $*" < "$command_script" || fail "Could not establish an ssh connection to $destination"
+            # Doesn't work, arguments aren't passed correctly:
+            # ssh -t "$destination" "/bin/bash -s -- $(<"$command_script")" "${longopts[*]}" "$*" || fail "Could not establish an ssh connection to $destination"
+            # The answer came from this under-appreciated comment on StackOverflow:
+            # https://unix.stackexchange.com/a/518960
+            ssh -qt "$destination" /bin/bash "<(echo "$(cat "$command_script" | base64 | tr -d '\n')" | base64 --decode)" "${longopts[*]}" "$*"
+        done
+    fi
 fi
 
 if [ $batch -eq 0 ]; then
