Add shellcheck integration and inject some utility functions into cached scripts (with an additional shellcheck). Ensure that function variables are local.

diff --git a/golem b/golem
--- a/golem
+++ b/golem
@@ -13,25 +13,12 @@ scriptname=$(basename "$_")
 # And the path.
 scriptpath=$(readlink -m "$0")
 scriptdir=$(dirname "$scriptpath")
-# And the PID.
-golem_pid=$$
-
-# barf and exit if an undefined variable is referenced.
-set -u
-
-# if any command in a pipeline fails, that return code will be used as the
-# return code of the whole pipeline.
-set -o pipefail
 
 # restrict newly created files to read/write by this user only.
 umask 077
 
 # Batch (quiet) mode?
 batch=0
-
-# Halt if a TERM signal is received by this PID.
-trap "exit 1" TERM
-
 
 
 ################################################################################
@@ -125,12 +112,24 @@ _cache_check () {
                     fail "The shell file in $sourcefile has changed and the new version isn't passing shellcheck. Please run \"shellcheck $sourcefile\" and then try again."
                 fi
             fi
-            # Shellcheck succeeded or is not available, load this file into the cache.
+            # Shellcheck succeeded or is not available.
             cachedfile="$scriptdir/.cache/$file_basename.sh"
-            cp "$sourcefile" "$cachedfile"
+            # Inject the golem public code into this shell script.
+            # See https://unix.stackexchange.com/a/193498 for an explanation of
+            # this line noise.
+            warning="# Do not modify this file! This file is automatically generated from the source\n# file at $sourcefile.\n# Modify that file instead.\n"
+            sed -n "/^# begin-golem-injected-code$/,/^# end-golem-injected-code$/p" "$scriptpath" | xargs -0 printf "\n$warning\n%s\n" | sed '/^\s*[^#]\+/{;r /dev/stdin
+                N;:l;$!n;$!bl;};${;/^$/!{;s/\n$//;};//d;}' "$sourcefile" <(printf %s\\n) >"$cachedfile"
+            if [ -n "$shellcheck" ]; then
+                # Run shellcheck one more time on the completed cached file.
+                if ! $shellcheck "$cachedfile" >/dev/null 2>&1; then
+                    fail "There was a conflict between \"$sourcefile\" and the golem code that gets added to command scripts. Please run \"shellcheck $cachedfile\" and then try again."
+                fi
+            fi
         ;;
     esac
     if [ -n "$cachedfile" ]; then
+        chmod 0775 "$cachedfile"
         touch -r "$sourcefile" "$cachedfile"
     fi
     echo "$cachedfile"
@@ -168,10 +167,37 @@ _shell_resolve_cmd () {
 
 
 ##
+# The content between begin-golem-injected-code and end-golem-injected-code
+# gets inserted into the top of cached shell scripts.
+#
+# If shellcheck is available, then the cached scripts get shellchecked before
+# and after this code is inserted.
+#
+
+# begin-golem-injected-code
+
+# Exit with an error if an undefined variable is referenced.
+set -u
+
+# If any command in a pipeline fails, that return code will be used as the
+# return code for the whole pipeline.
+set -o pipefail
+
+# Store the script's PID; this is used in the fail() function to terminate
+# the script from subshells, loops, and the like.
+scriptpid=$$
+
+# Halt with a non-zero exit status if a TERM signal is received by this PID.
+# This is used by the fail() function along with $scriptpid.
+trap "exit 1" TERM
+
+
+##
 # Return the filename component of a path; this is identical to calling
 # "basename [path]"
 #
 path_filename () {
+    local path=""
     path=$(realpath -s -m "$1")
     echo "${path##*/}"
 }
@@ -182,6 +208,7 @@ path_filename () {
 # "dirname [path]", but it also cleans up extra slashes in the path.
 #
 path_directory () {
+    local filename=""
     filename=$(path_filename "$1")
     realpath -s -m "${1%$filename}"
 }
@@ -192,6 +219,7 @@ path_directory () {
 # "my_file" from "/path/to/my_file.txt".
 #
 path_basename () {
+    local filename="" base="" ext=""
     filename=$(path_filename "$1")
     base="${filename%%.[^.]*}"
     ext="${filename:${#base} + 1}"
@@ -208,6 +236,7 @@ path_basename () {
 # return ".tar.gz" for "my_file.tar.gz", and "" for ".test".
 #
 path_extension () {
+    local filename="" basename=""
     filename=$(path_filename "$1")
     basename=$(path_basename "$filename")
     echo "${filename##$basename}"
@@ -222,10 +251,11 @@ path_extension () {
 # Similar-looking characters are filtered out of the result string.
 #
 random_string () {
+    local -i num_chars=0
     if [ $# -gt 0 ]; then
-        local num_chars=$1
+        num_chars=$1
     else
-        local num_chars=$((12 + RANDOM % 12))
+        num_chars=$((12 + RANDOM % 12))
     fi
     tr -dc _A-Z-a-z-0-9 < /dev/urandom | tr -d '/+oO0lLiI1\n\r' | head -c $num_chars
 }
@@ -244,7 +274,7 @@ warn () {
 #
 fail () {
     echo "ERROR: $*" >&2
-    kill -s TERM $golem_pid
+    kill -s TERM $scriptpid
 }
 
 
@@ -262,11 +292,8 @@ ask () {
     #
     # ask() gives the answer in its exit status, e.g.,
     # if ask "Continue?"; then ...
-    local ans=""
-    local timeout=0
-    local required=0
-    local default=""
-    local prompt=""
+    local ans="" default="" prompt=""
+    local -i timeout=0 required=0
 
     while [[ "$1" ]]
     do
@@ -387,6 +414,7 @@ ask () {
     [[ "$ans" = "y" || "$ans" == "yes" ]]
 }
 
+# end-golem-injected-code
 
 ################################################################################
 #                                                                              #
@@ -418,8 +446,7 @@ if grep -q '^[[:space:]]*sudo ' "$command_script" && ! groups | grep -qw 'sudo';
     fail "It looks like this command requires superuser access and you're not in the 'sudo' group"
 fi
 
-# shellcheck disable=SC1090
-. "$command_script"
+/bin/bash "$command_script" "$*"
 
 if [ $batch -eq 0 ]; then
     echo
